FROM node:8.11

RUN apt-get update; \
  apt-get install -y \
    libgtk2.0-0 \
    libnotify-dev \
    libgconf-2-4 \
    libnss3 \
    libxss1 \
    libasound2 \
    xvfb

RUN mkdir /usr/src/app
WORKDIR /usr/src/app

RUN npm install cypress@3.1.0

COPY cypress /usr/src/app/cypress
COPY cypress.json /usr/src/app/cypress.json

RUN ./node_modules/.bin/cypress verify
